apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: speedfantsy-com-tls
spec:
  secretName: speedfantsy-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: speedfantsy.com
  dnsNames:
    - speedfantsy.com
    - www.speedfantsy.com