apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sydneyexch-com-tls
spec:
  secretName: sydneyexch-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: sydneyexch.com
  dnsNames:
    - sydneyexch.com
    - www.sydneyexch.com